project_id = "xmaqabhtozzykluuzmmg"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.process-ocr]
verify_jwt = true

[functions.generate-resource]
verify_jwt = true

[functions.create-billing]
verify_jwt = true

[functions.cakto-webhook]
verify_jwt = false

[functions.simulate-payment]
verify_jwt = true

[functions.list-billings]
verify_jwt = true

[functions.export-csv]
verify_jwt = true
